// Normal-mode primary-weapon values from OpenSoldat shared/Weapons.pas.
// Speed is converted to this project's world units by the simulation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WeaponStyle {
    Bullet,
    Shotgun,
    Explosive,
}

#[derive(Clone, Copy, Debug)]
pub struct Weapon {
    pub name: &'static str,
    pub fire_interval: u16,
    pub ammo: u16,
    pub reload_ticks: u16,
    pub speed: f32,
    pub hit_multiply: f32,
    pub startup_ticks: u16,
    pub style: WeaponStyle,
    pub pellets: u8,
}

pub const WEAPONS: [Weapon; 10] = [
    Weapon {
        name: "Desert Eagles",
        fire_interval: 24,
        ammo: 7,
        reload_ticks: 87,
        speed: 19.0,
        hit_multiply: 1.81,
        startup_ticks: 0,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "HK MP5",
        fire_interval: 6,
        ammo: 30,
        reload_ticks: 105,
        speed: 18.9,
        hit_multiply: 1.01,
        startup_ticks: 0,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "AK-74",
        fire_interval: 10,
        ammo: 35,
        reload_ticks: 165,
        speed: 24.6,
        hit_multiply: 1.004,
        startup_ticks: 0,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "Steyr AUG",
        fire_interval: 7,
        ammo: 25,
        reload_ticks: 125,
        speed: 26.0,
        hit_multiply: 0.71,
        startup_ticks: 0,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "SPAS-12",
        fire_interval: 32,
        ammo: 7,
        reload_ticks: 175,
        speed: 14.0,
        hit_multiply: 1.22,
        startup_ticks: 0,
        style: WeaponStyle::Shotgun,
        pellets: 6,
    },
    Weapon {
        name: "Ruger 77",
        fire_interval: 45,
        ammo: 4,
        reload_ticks: 78,
        speed: 33.0,
        hit_multiply: 2.49,
        startup_ticks: 0,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "M79",
        fire_interval: 6,
        ammo: 1,
        reload_ticks: 178,
        speed: 10.7,
        hit_multiply: 1550.0,
        startup_ticks: 0,
        style: WeaponStyle::Explosive,
        pellets: 1,
    },
    Weapon {
        name: "Barrett M82A1",
        fire_interval: 225,
        ammo: 10,
        reload_ticks: 70,
        speed: 55.0,
        hit_multiply: 4.45,
        startup_ticks: 19,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "FN Minimi",
        fire_interval: 9,
        ammo: 50,
        reload_ticks: 250,
        speed: 27.0,
        hit_multiply: 0.85,
        startup_ticks: 0,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
    Weapon {
        name: "XM214 Minigun",
        fire_interval: 3,
        ammo: 100,
        reload_ticks: 480,
        speed: 29.0,
        hit_multiply: 0.468,
        startup_ticks: 25,
        style: WeaponStyle::Bullet,
        pellets: 1,
    },
];
