//! The two default weapon tables, generated once from the pinned upstream configuration.
//!
//! Source: https://github.com/opensoldat/base server/configs/weapons.ini and server/configs/weapons_realistic.ini
//! Commit: `5b6e5bef23f5c0d58fb1d4d887b9b94ebcf799b4` (CC BY 4.0 — numeric configuration values derived for parity fixtures; no upstream assets redistributed)
//! Meaning: https://github.com/opensoldat/opensoldat shared/Weapons.pas (TGun, ORIGINAL_WEAPONS, BULLET_STYLE_*, BuildWeapons, CreateWMChecksum) at `c7596cdca32416cb66339b339105eb1e07e7fbbf`
//!
//! The same numbers are asserted field by field against `tests/fixtures/reference/weapons.json`
//! in `crates/game-core/tests/weapon_config_fixtures.rs`, so a typo here fails the build.

/// One weapon's sixteen configurable values, in `CONFIGURED_WEAPONS` order.
#[derive(Clone, Copy, Debug)]
pub(super) struct RawWeapon {
    pub damage: f32,
    pub fire_interval: u16,
    pub ammo: u8,
    pub reload_time: u16,
    pub speed: f32,
    pub bullet_style: u8,
    pub start_up_time: u16,
    pub bink: i16,
    pub movement_acc: f32,
    pub bullet_spread: f32,
    pub recoil: u16,
    pub push: f32,
    pub inherited_velocity: f32,
    pub modifier_head: f32,
    pub modifier_chest: f32,
    pub modifier_legs: f32,
}

/// `Default mod` version 1.7.1.
pub(super) const NORMAL: [RawWeapon; 20] = [
    // Desert Eagles
    RawWeapon {
        damage: 1.81,
        fire_interval: 24,
        ammo: 7,
        reload_time: 87,
        speed: 19.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.009,
        bullet_spread: 0.15,
        recoil: 0,
        push: 0.0176,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // HK MP5
    RawWeapon {
        damage: 1.01,
        fire_interval: 6,
        ammo: 30,
        reload_time: 105,
        speed: 18.9,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.14,
        recoil: 0,
        push: 0.0112,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // Ak-74
    RawWeapon {
        damage: 1.11,
        fire_interval: 11,
        ammo: 40,
        reload_time: 150,
        speed: 24.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.09,
        recoil: 0,
        push: 0.014,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // Steyr AUG
    RawWeapon {
        damage: 0.71,
        fire_interval: 7,
        ammo: 25,
        reload_time: 125,
        speed: 26.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.075,
        recoil: 0,
        push: 0.0084,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // Spas-12
    RawWeapon {
        damage: 1.22,
        fire_interval: 32,
        ammo: 7,
        reload_time: 175,
        speed: 14.0,
        bullet_style: 3,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.8,
        recoil: 0,
        push: 0.0188,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // Ruger 77
    RawWeapon {
        damage: 2.49,
        fire_interval: 39,
        ammo: 4,
        reload_time: 84,
        speed: 33.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.03,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.012,
        inherited_velocity: 0.5,
        modifier_head: 1.2,
        modifier_chest: 1.05,
        modifier_legs: 1.0,
    },
    // M79
    RawWeapon {
        damage: 1550.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 178,
        speed: 10.7,
        bullet_style: 4,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.036,
        inherited_velocity: 0.5,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Barret M82A1
    RawWeapon {
        damage: 4.45,
        fire_interval: 225,
        ammo: 10,
        reload_time: 70,
        speed: 55.0,
        bullet_style: 1,
        start_up_time: 19,
        bink: 65,
        movement_acc: 0.05,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.018,
        inherited_velocity: 0.5,
        modifier_head: 1.0,
        modifier_chest: 1.0,
        modifier_legs: 1.0,
    },
    // FN Minimi
    RawWeapon {
        damage: 0.85,
        fire_interval: 9,
        ammo: 50,
        reload_time: 250,
        speed: 27.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.013,
        bullet_spread: 0.064,
        recoil: 0,
        push: 0.0128,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // XM214 Minigun
    RawWeapon {
        damage: 0.468,
        fire_interval: 3,
        ammo: 100,
        reload_time: 480,
        speed: 29.0,
        bullet_style: 1,
        start_up_time: 25,
        bink: 0,
        movement_acc: 0.0625,
        bullet_spread: 0.3,
        recoil: 0,
        push: 0.0104,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // USSOCOM
    RawWeapon {
        damage: 1.49,
        fire_interval: 10,
        ammo: 14,
        reload_time: 60,
        speed: 18.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.02,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // Combat Knife
    RawWeapon {
        damage: 2150.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 3,
        speed: 6.0,
        bullet_style: 11,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.12,
        inherited_velocity: 0.0,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Chainsaw
    RawWeapon {
        damage: 50.0,
        fire_interval: 2,
        ammo: 200,
        reload_time: 110,
        speed: 8.0,
        bullet_style: 11,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0028,
        inherited_velocity: 0.0,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // M72 LAW
    RawWeapon {
        damage: 1550.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 300,
        speed: 23.0,
        bullet_style: 12,
        start_up_time: 13,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.028,
        inherited_velocity: 0.5,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Flamed Arrows
    RawWeapon {
        damage: 8.0,
        fire_interval: 10,
        ammo: 1,
        reload_time: 39,
        speed: 18.0,
        bullet_style: 8,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0,
        inherited_velocity: 0.5,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Rambo Bow
    RawWeapon {
        damage: 12.0,
        fire_interval: 10,
        ammo: 1,
        reload_time: 25,
        speed: 21.0,
        bullet_style: 7,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0148,
        inherited_velocity: 0.5,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Flamer
    RawWeapon {
        damage: 19.0,
        fire_interval: 6,
        ammo: 200,
        reload_time: 5,
        speed: 10.5,
        bullet_style: 5,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.016,
        inherited_velocity: 0.5,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Stationary Gun
    RawWeapon {
        damage: 1.8,
        fire_interval: 10,
        ammo: 100,
        reload_time: 366,
        speed: 36.0,
        bullet_style: 14,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0088,
        inherited_velocity: 0.0,
        modifier_head: 1.1,
        modifier_chest: 0.95,
        modifier_legs: 0.85,
    },
    // Punch
    RawWeapon {
        damage: 330.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 3,
        speed: 5.0,
        bullet_style: 6,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0,
        inherited_velocity: 0.0,
        modifier_head: 1.15,
        modifier_chest: 1.0,
        modifier_legs: 0.9,
    },
    // Grenade
    RawWeapon {
        damage: 1500.0,
        fire_interval: 80,
        ammo: 1,
        reload_time: 20,
        speed: 5.0,
        bullet_style: 2,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.0,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0,
        inherited_velocity: 1.0,
        modifier_head: 1.0,
        modifier_chest: 1.0,
        modifier_legs: 1.0,
    },
];

/// `Realistic mod` version 1.7.1.
pub(super) const REALISTIC: [RawWeapon; 20] = [
    // Desert Eagles
    RawWeapon {
        damage: 1.66,
        fire_interval: 27,
        ammo: 7,
        reload_time: 106,
        speed: 19.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.02,
        bullet_spread: 0.1,
        recoil: 55,
        push: 0.0164,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // HK MP5
    RawWeapon {
        damage: 0.94,
        fire_interval: 6,
        ammo: 30,
        reload_time: 110,
        speed: 18.9,
        bullet_style: 1,
        start_up_time: 0,
        bink: -10,
        movement_acc: 0.01,
        bullet_spread: 0.03,
        recoil: 9,
        push: 0.0164,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Ak-74
    RawWeapon {
        damage: 1.08,
        fire_interval: 11,
        ammo: 35,
        reload_time: 158,
        speed: 24.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: -10,
        movement_acc: 0.02,
        bullet_spread: 0.0,
        recoil: 13,
        push: 0.0132,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Steyr AUG
    RawWeapon {
        damage: 0.68,
        fire_interval: 7,
        ammo: 30,
        reload_time: 126,
        speed: 26.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: -9,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 11,
        push: 0.012,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Spas-12
    RawWeapon {
        damage: 1.2,
        fire_interval: 35,
        ammo: 7,
        reload_time: 175,
        speed: 13.2,
        bullet_style: 3,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.8,
        recoil: 65,
        push: 0.0224,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Ruger 77
    RawWeapon {
        damage: 2.22,
        fire_interval: 52,
        ammo: 4,
        reload_time: 104,
        speed: 33.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 14,
        movement_acc: 0.03,
        bullet_spread: 0.0,
        recoil: 54,
        push: 0.0096,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // M79
    RawWeapon {
        damage: 1600.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 173,
        speed: 11.4,
        bullet_style: 4,
        start_up_time: 0,
        bink: 45,
        movement_acc: 0.03,
        bullet_spread: 0.0,
        recoil: 420,
        push: 0.024,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Barret M82A1
    RawWeapon {
        damage: 4.95,
        fire_interval: 200,
        ammo: 10,
        reload_time: 170,
        speed: 55.0,
        bullet_style: 1,
        start_up_time: 16,
        bink: 80,
        movement_acc: 0.07,
        bullet_spread: 0.0,
        recoil: 0,
        push: 0.0056,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // FN Minimi
    RawWeapon {
        damage: 0.81,
        fire_interval: 10,
        ammo: 50,
        reload_time: 261,
        speed: 27.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: -8,
        movement_acc: 0.02,
        bullet_spread: 0.0,
        recoil: 8,
        push: 0.0116,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // XM214 Minigun
    RawWeapon {
        damage: 0.43,
        fire_interval: 4,
        ammo: 100,
        reload_time: 320,
        speed: 29.0,
        bullet_style: 1,
        start_up_time: 33,
        bink: -2,
        movement_acc: 0.01,
        bullet_spread: 0.1,
        recoil: 4,
        push: 0.0108,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // USSOCOM
    RawWeapon {
        damage: 1.3,
        fire_interval: 12,
        ammo: 12,
        reload_time: 72,
        speed: 18.0,
        bullet_style: 1,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.02,
        bullet_spread: 0.0,
        recoil: 28,
        push: 0.0172,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Combat Knife
    RawWeapon {
        damage: 2250.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 3,
        speed: 6.0,
        bullet_style: 11,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.028,
        inherited_velocity: 0.0,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Chainsaw
    RawWeapon {
        damage: 21.0,
        fire_interval: 2,
        ammo: 200,
        reload_time: 110,
        speed: 7.6,
        bullet_style: 11,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 1,
        push: 0.0028,
        inherited_velocity: 0.0,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // M72 LAW
    RawWeapon {
        damage: 1500.0,
        fire_interval: 30,
        ammo: 1,
        reload_time: 495,
        speed: 23.0,
        bullet_style: 12,
        start_up_time: 12,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 9,
        push: 0.012,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Flamed Arrows
    RawWeapon {
        damage: 8.0,
        fire_interval: 10,
        ammo: 1,
        reload_time: 39,
        speed: 18.0,
        bullet_style: 8,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.0,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Rambo Bow
    RawWeapon {
        damage: 12.0,
        fire_interval: 10,
        ammo: 1,
        reload_time: 25,
        speed: 21.0,
        bullet_style: 7,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.0148,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Flamer
    RawWeapon {
        damage: 12.0,
        fire_interval: 6,
        ammo: 200,
        reload_time: 5,
        speed: 12.5,
        bullet_style: 5,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.016,
        inherited_velocity: 0.5,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Stationary Gun
    RawWeapon {
        damage: 1.55,
        fire_interval: 14,
        ammo: 100,
        reload_time: 366,
        speed: 36.0,
        bullet_style: 14,
        start_up_time: 21,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.0088,
        inherited_velocity: 0.0,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Punch
    RawWeapon {
        damage: 330.0,
        fire_interval: 6,
        ammo: 1,
        reload_time: 3,
        speed: 5.0,
        bullet_style: 6,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.0,
        inherited_velocity: 0.0,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
    // Grenade
    RawWeapon {
        damage: 1500.0,
        fire_interval: 80,
        ammo: 1,
        reload_time: 20,
        speed: 5.0,
        bullet_style: 2,
        start_up_time: 0,
        bink: 0,
        movement_acc: 0.01,
        bullet_spread: 0.0,
        recoil: 10,
        push: 0.0,
        inherited_velocity: 1.0,
        modifier_head: 1.1,
        modifier_chest: 1.0,
        modifier_legs: 0.6,
    },
];

pub(super) const NORMAL_NAME: &str = "Default mod";
pub(super) const REALISTIC_NAME: &str = "Realistic mod";
pub(super) const DEFAULT_VERSION: &str = "1.7.1";
