// Which file every sprite comes from, how big it is meant to be drawn, and what a mod is allowed
// to change about that.
//
// The manifest is the only place a filename appears. Nothing else in the renderer knows where art
// lives, which is what lets a mod replace a sprite without touching a line of drawing code.

export type AssetEntry = {
  id: string
  /// Path under the public root.
  path: string
  /// How many world units one pixel of the source image covers when drawn at scale 1.
  scale: number
  /// Whether this asset is generated by this project rather than imported from anywhere.
  generated: boolean
}

export type AssetManifest = {
  version: number
  entries: Record<string, AssetEntry>
}

function entry(id: string, path: string, scale = 1): AssetEntry {
  return { id, path, scale, generated: true }
}

/// The stock manifest. Every entry is art generated for this project; nothing upstream is shipped.
export function defaultManifest(): AssetManifest {
  const entries: AssetEntry[] = [
    entry('soldier', 'art/soldier.png'),
    entry('backdrop', 'art/battlefield.png'),
    entry('key-art', 'art/arena-key-art.png'),
  ]
  return {
    version: 1,
    entries: Object.fromEntries(entries.map(asset => [asset.id, asset])),
  }
}

export function assetPath(manifest: AssetManifest, id: string): string | null {
  return manifest.entries[id]?.path ?? null
}

/// How big a sprite is drawn, in world units, after the manifest's own scale and any mod rule.
export function drawSize(
  manifest: AssetManifest,
  id: string,
  pixels: { width: number; height: number },
): { width: number; height: number } {
  const scale = manifest.entries[id]?.scale ?? 1
  return { width: pixels.width * scale, height: pixels.height * scale }
}

/// A mod's own rules, in the shape the original's `mod.ini` used: a scale per asset, and a default
/// for everything it does not name.
export type ModRules = {
  name: string
  defaultScale?: number
  scales?: Record<string, number>
  /// Replacement paths, relative to the mod's own directory.
  replace?: Record<string, string>
}

export type ModError = { asset: string; reason: string }

const MIN_MOD_SCALE = 0.25
const MAX_MOD_SCALE = 4

/// Applies a mod to the manifest.
///
/// A mod may re-point and re-scale an asset that exists; it may not invent one, because a sprite
/// nothing draws is a file the player downloaded for nothing, and it may not scale one out of all
/// proportion, because a soldier the size of the map is a cheat rather than a mod.
export function applyMod(
  manifest: AssetManifest,
  mod: ModRules,
): { manifest: AssetManifest } | { errors: ModError[] } {
  const errors: ModError[] = []
  const entries: Record<string, AssetEntry> = {}
  const base = mod.defaultScale ?? 1
  if (!Number.isFinite(base) || base < MIN_MOD_SCALE || base > MAX_MOD_SCALE) {
    errors.push({ asset: '(default)', reason: `scale must be between ${MIN_MOD_SCALE} and ${MAX_MOD_SCALE}` })
  }
  for (const [id, scale] of Object.entries(mod.scales ?? {})) {
    if (!manifest.entries[id]) {
      errors.push({ asset: id, reason: 'no such asset' })
    } else if (!Number.isFinite(scale) || scale < MIN_MOD_SCALE || scale > MAX_MOD_SCALE) {
      errors.push({ asset: id, reason: `scale must be between ${MIN_MOD_SCALE} and ${MAX_MOD_SCALE}` })
    }
  }
  for (const id of Object.keys(mod.replace ?? {})) {
    if (!manifest.entries[id]) errors.push({ asset: id, reason: 'no such asset' })
  }
  for (const [id, path] of Object.entries(mod.replace ?? {})) {
    if (path.includes('..') || path.startsWith('/') || /^[a-z]+:/i.test(path)) {
      errors.push({ asset: id, reason: 'a replacement must stay inside the mod directory' })
    }
  }
  if (errors.length > 0) return { errors }

  for (const [id, asset] of Object.entries(manifest.entries)) {
    const replacement = mod.replace?.[id]
    entries[id] = {
      ...asset,
      path: replacement ? `mods/${mod.name}/${replacement}` : asset.path,
      scale: asset.scale * (mod.scales?.[id] ?? base),
      generated: replacement ? false : asset.generated,
    }
  }
  return { manifest: { version: manifest.version, entries } }
}

/// The assets that came from outside this project, which is exactly the list a provenance record
/// has to account for.
export function importedAssets(manifest: AssetManifest): string[] {
  return Object.values(manifest.entries)
    .filter(asset => !asset.generated)
    .map(asset => asset.id)
    .sort()
}

/// A custom interface: a HUD atlas and the graphics that go with it.
///
/// It is kept apart from the sprite manifest, because replacing a health bar is a cosmetic choice
/// and replacing a soldier changes what other players look like.
export type InterfaceSkin = {
  name: string
  /// Sprite ids this skin provides, drawn instead of the built-in shapes.
  provides: string[]
}

export const INTERFACE_SLOTS = [
  'hud-health',
  'hud-jet',
  'hud-ammo',
  'hud-frame',
  'hud-crosshair',
  'hud-minimap',
] as const

export function readInterfaceSkin(source: unknown): { skin: InterfaceSkin } | { errors: ModError[] } {
  const data = source as { name?: unknown; provides?: unknown }
  if (typeof data !== 'object' || data === null || !Array.isArray(data.provides)) {
    return { errors: [{ asset: '(document)', reason: 'expected a name and a list of provided slots' }] }
  }
  const errors: ModError[] = []
  const provides: string[] = []
  for (const slot of data.provides as unknown[]) {
    if (typeof slot !== 'string' || !(INTERFACE_SLOTS as readonly string[]).includes(slot)) {
      errors.push({ asset: String(slot), reason: 'not an interface slot this game draws' })
      continue
    }
    provides.push(slot)
  }
  if (errors.length > 0) return { errors }
  return {
    skin: { name: typeof data.name === 'string' && data.name ? data.name : 'custom', provides },
  }
}

/// Whether a slot is drawn by a skin or by the built-in shapes.
export function slotSource(skin: InterfaceSkin | null, slot: string): 'skin' | 'builtin' {
  return skin && skin.provides.includes(slot) ? 'skin' : 'builtin'
}
